package VetPet;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DatabaseMetaData;
import javax.swing.JOptionPane;

public class NewJFrame extends javax.swing.JFrame {

    DatabaseMetaData dbm;
    Connection con;
    Statement stmt, STMT;
    ResultSet rs;
    int curRow;
    
    public NewJFrame() {
        initComponents();
        doConnect();
    }
    
    public void doConnect(){
        
        try{
            
            //CONNECT TO DATABASE
            con = DriverManager.getConnection("jdbc:derby:vet_database1;create=true;");
           
            //CHECK IF TABLE ALREADY EXISTS AND ADD A DEFAULT ROW IF IT DOESN'T
            STMT =con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            dbm = con.getMetaData();
            ResultSet tables = dbm.getTables(null, null, "PELATES", null);
            if(!tables.next()){
                String createTable="CREATE TABLE PELATES (arithmos INT, onomatepwnumo VARCHAR(100),dieuthinsi VARCHAR(100), stathero BIGINT, kinito BIGINT, pontoi INT, xbonus INT, xreos DOUBLE)";
                String insertRow = "INSERT INTO PELATES VALUES (1, 'ΟΝΟΜΑ', 'ΔΙΕΥΘΥΝΣΗ', 0, 0, 0, 0, 0)";
                STMT.executeUpdate(createTable);
                STMT.executeUpdate(insertRow);
                STMT.close();
            }
            
            Reload();
          
        }
        catch(SQLException err){
            
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }
    
    public void Reload(){
        try{
            
            //EXECUTE SQL, LOAD INTO THE RESULTSET OBJECT
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rs = stmt.executeQuery("SELECT * FROM PELATES");
            
            //MOVE CURSOR TO FIRST ROW, ADD ALL THE DATA
            rs.next();
            set();
        }
        catch(SQLException err){
            
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
        
    }
    
    public void set(){
        try{
            
            textCard.setText(Integer.toString(rs.getInt(1)));
            textName.setText(rs.getString(2));
            textAddress.setText(rs.getString(3));
            textHome.setText(Long.toString(rs.getLong(4)));
            textMobile.setText(Long.toString(rs.getLong(5)));
            textPoints.setText(Integer.toString(rs.getInt(6)));
            textBonus.setText(Integer.toString(rs.getInt(7)));
            textDebt.setText(Double.toString(rs.getDouble(8)));
            
            
            int pos = rs.getRow();
            rs.beforeFirst();
            int total=0;
            while(rs.next()){
                total++;
            }
            rs.absolute(pos);
            TextAll.setText(Integer.toString(total));
                        
        }
        catch(SQLException err){
            JOptionPane.showMessageDialog(NewJFrame.this, err.getMessage());
        }
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textCard = new javax.swing.JTextField();
        textName = new javax.swing.JTextField();
        textAddress = new javax.swing.JTextField();
        textHome = new javax.swing.JTextField();
        textMobile = new javax.swing.JTextField();
        textPoints = new javax.swing.JTextField();
        textBonus = new javax.swing.JTextField();
        textDebt = new javax.swing.JTextField();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        TextCurrent = new javax.swing.JTextField();
        TextAll = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        btnAddClient = new javax.swing.JButton();
        btnSearchName = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 6), new java.awt.Dimension(0, 6), new java.awt.Dimension(32767, 6));
        btnSearchNumber = new javax.swing.JButton();
        btnAddPoints = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Αριθμός Κάρτας");

        jLabel2.setText("Ονοματεπώνυμο");

        jLabel4.setText("Διεύθυνση");

        jLabel5.setText("Σταθερό");

        jLabel6.setText("Κινητό");

        jLabel7.setText("Πόντοι");

        jLabel8.setText("xBONUS");

        jLabel9.setText("Χρέος");

        textCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCardActionPerformed(evt);
            }
        });

        textAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAddressActionPerformed(evt);
            }
        });

        btnPrevious.setText("Προηγούμενο");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setText("Επόμενο");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnStart.setText("Αρχή");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnLast.setText("Τέλος");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        TextCurrent.setText("1");
        TextCurrent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCurrentActionPerformed(evt);
            }
        });

        TextAll.setText("total");

        jLabel3.setText("από");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textPoints)
                            .addComponent(textMobile)
                            .addComponent(textHome)
                            .addComponent(textAddress)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(59, 59, 59)
                        .addComponent(textBonus))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(71, 71, 71)
                        .addComponent(textDebt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPrevious)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textCard)
                                    .addComponent(textName)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLast)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textDebt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevious)
                    .addComponent(btnNext))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(btnLast))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );

        jToolBar1.setRollover(true);

        btnAddClient.setText("Προσθήκη πελάτη");
        btnAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClientActionPerformed(evt);
            }
        });

        btnSearchName.setText("Αναζήτηση με Όνομα");
        btnSearchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchNameActionPerformed(evt);
            }
        });

        btnDelete.setText("Διαγραφή");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSearchNumber.setText("Αναζήτηση με Κάρτα");
        btnSearchNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchNumberActionPerformed(evt);
            }
        });

        btnAddPoints.setText("Πρόσθεση Πόντων");
        btnAddPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPointsActionPerformed(evt);
            }
        });

        btnConfirm.setText("Επιβεβαίωση");
        btnConfirm.setEnabled(false);
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnCancel.setText("Ακύρωση");
        btnCancel.setEnabled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearchName, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(btnSearchNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddPoints, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnConfirm)
                .addGap(18, 18, 18)
                .addComponent(btnCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddClient)
                    .addComponent(btnConfirm)
                    .addComponent(btnCancel))
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addGap(18, 18, 18)
                .addComponent(btnSearchName)
                .addGap(18, 18, 18)
                .addComponent(btnSearchNumber)
                .addGap(18, 18, 18)
                .addComponent(btnAddPoints)
                .addGap(34, 34, 34)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jToolBar1.add(jPanel2);

        btnSave.setText("Αποθήκευση");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(101, 101, 101)
                        .addComponent(btnSave))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClientActionPerformed
        
        try{
            curRow = rs.getRow();
            
            textCard.setText("");
            textName.setText("");
            textAddress.setText("");
            textHome.setText("");
            textMobile.setText("");
            textPoints.setText("");
            textBonus.setText("");
            textDebt.setText("");
            
            //DISABLE BUTTONS
            btnPrevious.setEnabled( false );
            btnNext.setEnabled( false );
            btnStart.setEnabled( false );
            btnLast.setEnabled( false );
            btnDelete.setEnabled( false );
            btnSearchName.setEnabled( false );
            btnSearchNumber.setEnabled( false );
            btnSave.setEnabled( false );
            btnAddPoints.setEnabled( false );
            btnAddClient.setEnabled( false );
        
            //ENABLE BUTTONS
            btnConfirm.setEnabled( true );
            btnCancel.setEnabled( true );
        }
        catch(SQLException err){
            JOptionPane.showMessageDialog(NewJFrame.this, err.getMessage());
        }
        
        
    }//GEN-LAST:event_btnAddClientActionPerformed

    private void textCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCardActionPerformed

    private void textAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAddressActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        try{
            if(rs.previous()){
                set();
                String pos =Integer.toString(rs.getRow());
                TextCurrent.setText(pos);
            }
            else{
                rs.next();
            }
                
        }
        catch(SQLException err){
            JOptionPane.showMessageDialog(NewJFrame.this, err.getMessage());
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        try{
            if(rs.next()){
                set();
                String pos =Integer.toString(rs.getRow());
                TextCurrent.setText(pos);
            }
            else{
                rs.previous();
            }
                
        }
        catch(SQLException err){
            JOptionPane.showMessageDialog(NewJFrame.this, err.getMessage());
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        try{
            rs.first();
            set();
        }
        catch(SQLException err){
            JOptionPane.showMessageDialog(NewJFrame.this, err.getMessage());
        }
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        try{
            rs.last();
            set();
        }
        catch(SQLException err){
            JOptionPane.showMessageDialog(NewJFrame.this, err.getMessage());
        }
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        int number = Integer.parseInt(textCard.getText());
        String name = textName.getText();
        String address = textAddress.getText();
        long home = Long.parseLong(textHome.getText());
        long mobile = Long.parseLong(textMobile.getText());
        int points = Integer.parseInt(textPoints.getText());
        int bonus = Integer.parseInt(textBonus.getText());
        double debt = Double.parseDouble(textDebt.getText());
        
        try{
            int pos = rs.getRow();
            rs.updateInt(1, number);
            rs.updateString(2, name);
            rs.updateString(3, address);
            rs.updateLong(4, home);
            rs.updateLong(5, mobile);
            rs.updateInt(6, points);
            rs.updateInt(7, bonus);
            rs.updateDouble(8, debt);
            rs.updateRow();
            JOptionPane.showMessageDialog(null, "Αποθηκεύτηκε!");
            
            stmt.close();
            rs.close();
            
            Reload();
            rs.absolute(pos);
            set();
            
        }
        catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSearchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchNameActionPerformed
        
        try{
            int pos = rs.getRow();
            String n=JOptionPane.showInputDialog(null,"Δώσε Όνομα");
            rs.beforeFirst();
            boolean s=false;
            
            while(rs.next()){
               
                if(n.equals(rs.getString(2))){
                    set();
                    TextCurrent.setText(Integer.toString(rs.getRow()));
                    s=true;
                    break;
                    
               }
            }
            if(s==false){
                JOptionPane.showMessageDialog(null, "ΔΕ ΒΡΕΘΗΚΕ");
                rs.absolute(pos);
                
            }
        }
        catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }//GEN-LAST:event_btnSearchNameActionPerformed

    private void btnSearchNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchNumberActionPerformed
        try{
            int pos = rs.getRow();
            rs.beforeFirst();
            int count=0;
            while (rs.next()){
                count++;
            }
            rs.first();
            String str=JOptionPane.showInputDialog(null,"Εισαγωγή Αριθμού Κάρτας" );
            int n= Integer.parseInt(str);
            
            if(n<=count){
                rs.absolute(n);
                set();
                TextCurrent.setText(Integer.toString(rs.getRow()));
            }
            else{
                JOptionPane.showMessageDialog(null, "Δεν υπάρχει ο αριθμός");
                rs.absolute(pos);
            }
        }
        catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }//GEN-LAST:event_btnSearchNumberActionPerformed

    private void btnAddPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPointsActionPerformed
        try{
            int AddPoints = Integer.parseInt(JOptionPane.showInputDialog(null, "Πόσοι πόντοι να προσθεθούν;"));
        
            int Points=Integer.parseInt(rs.getString(6));
            Points+=AddPoints;
            
            if(Points>=800){
                JOptionPane.showMessageDialog(null,"O πελάτης "+ rs.getString(2)+" κέρδισε 2 BONUS!","BONUS",JOptionPane.INFORMATION_MESSAGE);
                Points-=800;
                //ΑΥΞΗΣΕ ΤΟ ΒΟΝUS ΚΑΤΑ 2
                int bon=Integer.parseInt(textBonus.getText());
                bon+=2;
                rs.updateInt(7, bon);
            }
            
            else if(Points>=400){
                JOptionPane.showMessageDialog(null,"O πελάτης "+ rs.getString(2)+" κέρδισε BONUS!","BONUS",JOptionPane.INFORMATION_MESSAGE);
                Points-=400;
                //ΑΥΞΗΣΕ ΤΟ ΒΟΝUS ΚΑΤΑ 1
                int bon=Integer.parseInt(textBonus.getText());
                bon++;
                rs.updateInt(7, bon);
            }
            
            rs.updateInt(6, Points);
            set();
        }
        catch(SQLException err){
            JOptionPane.showMessageDialog(null,err.getMessage());
        }
    }//GEN-LAST:event_btnAddPointsActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        try{
            int pos = rs.getRow();
            rs.deleteRow();
            stmt.close();
            rs.close();
            
            Reload();
            rs.absolute(pos-1);
            set();
            TextCurrent.setText(Integer.toString(pos-1));
        }
        catch(SQLException err){
            JOptionPane.showMessageDialog(NewJFrame.this, err.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        try{
            
            rs.absolute(curRow);
            set();
            //DISABLE BUTTONS
            btnPrevious.setEnabled( true );
            btnNext.setEnabled( true );
            btnStart.setEnabled( true );
            btnLast.setEnabled( true );
            btnDelete.setEnabled( true );
            btnSearchName.setEnabled( true );
            btnSearchNumber.setEnabled( true );
            btnSave.setEnabled( true );
            btnAddPoints.setEnabled( true );
            btnAddClient.setEnabled( true );
        
            //ENABLE BUTTONS
            btnConfirm.setEnabled( false );
            btnCancel.setEnabled( false );
        }
        catch(SQLException err){
            JOptionPane.showMessageDialog(NewJFrame.this, err.getMessage());
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        
        int number = Integer.parseInt(textCard.getText());
        String name = textName.getText();
        String address = textAddress.getText();
        long home = Long.parseLong(textHome.getText());
        long mobile = Long.parseLong(textMobile.getText());
        int points = Integer.parseInt(textPoints.getText());
        int bonus = Integer.parseInt(textBonus.getText());
        double debt = Double.parseDouble(textDebt.getText());
        
        try{
            int pos = rs.getRow();
            rs.moveToInsertRow();
            
            rs.updateInt(1, number);
            rs.updateString(2, name);
            rs.updateString(3, address);
            rs.updateLong(4, home);
            rs.updateLong(5, mobile);
            rs.updateInt(6, points);
            rs.updateInt(7, bonus);
            rs.updateDouble(8, debt);
                        
            rs.insertRow();
            stmt.close();
            rs.close();
            
            Reload();
            rs.absolute(pos+1);
            set();
            TextCurrent.setText(Integer.toString(pos+1));
            
            //DISABLE BUTTONS
            btnPrevious.setEnabled( true );
            btnNext.setEnabled( true );
            btnStart.setEnabled( true );
            btnLast.setEnabled( true );
            btnDelete.setEnabled( true );
            btnSearchName.setEnabled( true );
            btnSearchNumber.setEnabled( true );
            btnSave.setEnabled( true );
            btnAddPoints.setEnabled( true );
            btnAddClient.setEnabled( true );
        
            //ENABLE BUTTONS
            btnConfirm.setEnabled( false );
            btnCancel.setEnabled( false );
            
        }
        catch(SQLException err){
            JOptionPane.showMessageDialog(NewJFrame.this, err.getMessage());
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void TextCurrentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCurrentActionPerformed
        
    }//GEN-LAST:event_TextCurrentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextAll;
    private javax.swing.JTextField TextCurrent;
    private javax.swing.JButton btnAddClient;
    private javax.swing.JButton btnAddPoints;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearchName;
    private javax.swing.JButton btnSearchNumber;
    private javax.swing.JButton btnStart;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField textAddress;
    private javax.swing.JTextField textBonus;
    private javax.swing.JTextField textCard;
    private javax.swing.JTextField textDebt;
    private javax.swing.JTextField textHome;
    private javax.swing.JTextField textMobile;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textPoints;
    // End of variables declaration//GEN-END:variables
}
